# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "thabo-terragrunt-state"
    dynamodb_table = ""
    encrypt        = false
    key            = "af-south-1/kms_key/terraform.tfvars"
    profile        = "default"
    region         = "af-south-1"
  }
}
